drop table IF EXISTS users cascade;
drop table IF EXISTS items cascade;
drop table IF EXISTS bookings cascade;
drop table IF EXISTS requests cascade;
drop table IF EXISTS comments cascade;

create TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(512) UNIQUE NOT NULL
 );

create TABLE IF NOT EXISTS items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(512) NOT NULL,
    available BOOLEAN,
    owner_id BIGINT REFERENCES users(id) ON delete CASCADE,
    request_id BIGINT
);


create TABLE IF NOT EXISTS bookings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT REFERENCES items(id) ON delete CASCADE,
    booker_id BIGINT REFERENCES users(id) ON delete CASCADE,
    status varchar(55) NOT NULL
);

create TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(512) NOT NULL,
    requestor_id BIGINT REFERENCES users(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(512) NOT NULL,
    created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    item_id BIGINT REFERENCES items(id) ON delete CASCADE,
    author_id BIGINT REFERENCES users(id) ON delete CASCADE
);